### ISSUE TITLE
Unable to run the Stream API sample

### ISSUE THREAD

**Issue by cfu1** [ryanmcgrath/twython#144]
Hi, I'm testing the stream API sample code here https://github.com/ryanmcgrath/twython, but keep getting this error: line 560, in stream TwythonError: 'Response was not valid JSON, unable to decode.' Any help is appreciated.

**Comment by surank** [comment]
so im trying to stream and I'm using the exact same code as above, ive used Twython before to fetch data using the search function...

from twython import TwythonStreamer

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            print data['text'].encode('utf-8')

    def on_error(self, status_code, data):
        print status_code, data

stream = MyStreamer(APP_KEY, APP_SECRET,
                    OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

stream.statuses.filter(track='#fashion')

but i am not seeing any data....
