### ISSUE TITLE
Error 401 when using TwythonStreamer

### ISSUE THREAD

**Issue by joncasdam** [ryanmcgrath/twython#237]
Hello, I know that recently a very similar issue was close, but I think it is different.

What happens is that when I try to work with TwythonStreamer - exactly like tutorial, I'm receiving the error 401.

The credentials are ok, since it works nicely with basic usage tutorial.

I'm with:

> python=2.7.3
> requests=1.2.0
> requests_oauthlib=0.3.2
> oauthlib=0.4.2

ps: I've found a question at Stackoverflow with the same question http://stackoverflow.com/questions/17438943/twython-oauth1-issues-401-error-using-example-code

**Comment by martinconzelmann** [comment]
Thanks @keonne for this solution!

**Comment by keonne** [comment]
@martinconzelmann Happy to help!
