### ISSUE TITLE
Error: Unable to obtain OAuth 2 access token

### ISSUE THREAD

**Issue by ExDepp** [ryanmcgrath/twython#239]
I'm working on a GUI to read tweets, based on python 2.7.

When I run the script via Eclipse an PyDev, everything works fine. But after compiling it with gui2exe/py2exe, I get this error message:

```
twython.exceptions.TwythonAuthError: Unable to obtain OAuth 2 access token
```

The code is:

<pre><code>
     CONSUMER_KEY = '****'
    CONSUMER_SECRET = '****'
    ACCESS_KEY = '****'
    ACCESS_SECRET = '****'
    twitter = Twython(CONSUMER_KEY, CONSUMER_SECRET, oauth_version=2)
    ACCESS_TOKEN = twitter.obtain_access_token()
    if settings.value("Proxys").toBool() == True:
        httpproxy = settings.value ("HttpProxy").toString()
        httpsproxy = settings.value ("HttpsProxy").toString()
        proxystring = "'http': '%s','https': '%s'" % (httpproxy, httpsproxy)
        client_args = {
                       'proxies': {
                                   proxystring,
                                   }
                       }
        self.api = Twython(CONSUMER_KEY, access_token=ACCESS_TOKEN, client_args=client_args)
    else:
        self.api = Twython(CONSUMER_KEY, access_token=ACCESS_TOKEN)
</code></pre>

It's Python 2.7, twython 3.0, requests 1.2.3, request_oauthlib 0.3.2

**Comment by fibears** [comment]
I meet the similar question.

I get this error message:
 `twython.exceptions.TwythonAuthError: Unable to obtain OAuth 2 access token.`

My code is:

     `def twitter_auth2(): 
    secrets=my_secrets()

    APP_KEY=secrets['APP_KEY']
    APP_SECRET=secrets['APP_SECRET']
    my_access_token_key=secrets['my_access_token_key']
    my_access_token_secret=secrets['my_access_token_secret']

    twitter = Twython(APP_KEY, APP_SECRET,oauth_version=2)
    ACCESS_TOKEN = twitter.obtain_access_token()
    twitter = Twython(APP_KEY,access_token=ACCESS_TOKEN)

    return twitter`

Thanks.

**Comment by Tjorriemorrie** [comment]
Also getting this:
```
  File "/Users/jaco/projects/twurl/gae/lib/twython/api.py", line 410, in obtain_access_token
    raise TwythonAuthError('Unable to obtain OAuth 2 access token.')
TwythonAuthError: Unable to obtain OAuth 2 access token.
```

```
        from twython import Twython
        twitter = Twython(consumer_key, consumer_secret, oauth_version=2)
        ACCESS_TOKEN = twitter.obtain_access_token()
        app.logger.info('Access token: {}'.format(ACCESS_TOKEN))
```
