### ISSUE TITLE
Twitter API returned a 404

### ISSUE THREAD

**Issue by ghost** [ryanmcgrath/twython#253]
So...while using Twython I call create_list_members on a twython object. This error is invoked "Twitter API returned a 404 (Not Found), Sorry, that page does not exist". 

Any ideas as to where I'm going wrong? Thanks for reading this.

**Comment by graingerkid** [comment]
I'm getting this same error, however the the docs say the following...

> Causes the list of connections to be broken into pages of no more than 5000 IDs at a time. The number of IDs returned is not guaranteed to be 5000 as suspended users are filtered out after connections are queried. If no cursor is provided, a value of -1 will be assumed, which is the first “page.”

for the get_friends_ids() https://dev.twitter.com/rest/reference/get/friends/ids method, so suspended users should be removed, in my case at least - any other thoughts on this?
