### ISSUE TITLE
Help with streaming api disconnect() method

### ISSUE THREAD

**Issue by ErrorSoul** [ryanmcgrath/twython#291]
Hi there. I have some problem with disconnect(). How i can stop my stream manually with disconnect()? how i should design my program that i can to send self.connected= False inside MyStreamer? I understand that stream.user() is infinity loop  and i have no idea. 
```python

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            print data['text'].encode('utf-8')

    def on_error(self, status_code, data):
        print status_code

stream = MyStreamer(APP_KEY, APP_SECRET,
                    OAUTH_TOKEN, OAUTH_TOKEN_SECRET)
stream.user()
```

**Comment by sharkwheels** [comment]
I sort of have this issue as well. Mainly if the connection terminates on error, does it try to auto reconnect? Do I need to create a method to try and reconnect it? If that's the case could an example be included into the documentation? (sorry if this is a boring question addition).
