### ISSUE TITLE
can't except TwythonError

### ISSUE THREAD

**Issue by armujahid** [ryanmcgrath/twython#295]
My code is 

try:
    api.update_status_with_media(status='hello', media=photo)
except TwythonError:
            print 'error occured'

Whenever the exception occurred (when i intentionally run this code offline)than python says
(NameError: name 'TwythonError' is not defined)
please help

**Comment by ZacharyST** [comment]
> sorry i forgot to import TwythonError

Can you please show how you imported it?

**Comment by armujahid** [comment]
> > sorry i forgot to import TwythonError
> 
> Can you please show how you imported it?

`from twython import TwythonError`
