### ISSUE TITLE
Twitter API returned a 401 (Unauthorized) when trying to get users's friends on twitter

### ISSUE THREAD

**Issue by debunge** [ryanmcgrath/twython#318]
I'm using the following code which for a while worked like charm, but recently in 9 of the 10 attempts I'm getting error from twitter api

```
from twython import Twython, TwythonError                                                                             
from pymongo import Connection                                                                                        
import pika, time                                                                                                     

connection = Connection("host")
connection.admin.authenticate('admin', 'passwords')
db = connection['tweets']

consumer_key="key"
consumer_secret="secret"

access_token="token"
access_token_secret="secret_token"

t = Twython(app_key=consumer_key,
            app_secret=consumer_secret,
            oauth_token=access_token,
            oauth_token_secret=access_token_secret 
           )

Q ='download_friends'

r_connection = pika.BlockingConnection(pika.ConnectionParameters(
               'host'))
channel = r_connection.channel()
channel.queue_declare(queue= Q, 
                arguments={'x-message-ttl':600000})   


while 1:
    method_frame, header_frame, id = channel.basic_get(Q)
    if db.friends.find_one({"_id": id}) != None:
        print "Panic, user already exists"
        continue
    try:
        r = t.get_friends_list(user_id = id)
    except Exception as ex:
        print ex, id
    else:
        print id
        r['_id'] = id
        r['time'] = time.time()
        db.friends.save(r)

    time.sleep(121)
```

> Twitter API returned a 401 (Unauthorized), An error occurred
> processing your request.

Here is a stacktrace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/twython/endpoints.py", line 290, in get_friends_list
    return self.get('friends/list', params=params)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 230, in get
    return self.request(endpoint, params=params, version=version)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 224, in request
    content = self._request(url, method=method, params=params, api_call=url)
  File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 194, in _request
    retry_after=response.headers.get('retry-after'))
twython.exceptions.TwythonAuthError: Twitter API returned a 401 (Unauthorized), An error occurred processing your request.
```

I the remaining 1 attempt I'm actually getting a user's friends. 

I've googled a bit and corrected time on the machine (as they say one of the most common causes of this error), yet error still persists.

Also there is minimal not working example:

```
twitter = Twython('API key', 'API secret', oauth_version=2)
ACCESS_TOKEN = twitter.obtain_access_token()

print ACCESS_TOKEN

t = Twython('API key', access_token=ACCESS_TOKEN)
r = t.get_friends_list(user_id = 'id')
```

It is able to get ACCESS_TOKEN but nothing more.

**Comment by algarecu** [comment]
See Twitter’s API details on this: has your token expired?

API request contains invalid bearer token
Using an incorrect or revoked bearer token to make API requests will result in:

HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Content-Length: 61
...

{"errors":[{"message":"Invalid or expired token","code":89}]}

**Comment by aseempatni** [comment]
I'm using 

    APP_KEY = '****'
    ACCESS_TOKEN = '****'
    twitter = Twython(APP_KEY, access_token=ACCESS_TOKEN)
    twitter.search(q='python')

Getting 401. Here's the trace:

    File "get_user_data.py", line 8, in <module>
      twitter.search(q='python')
    File "/usr/local/lib/python2.7/dist-packages/twython/endpoints.py", line 169, in search
      return self.get('search/tweets', params=params)
    File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 265, in get
      return self.request(endpoint, params=params, version=version)
    File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 259, in request
      api_call=url)
    File "/usr/local/lib/python2.7/dist-packages/twython/api.py", line 198, in _request
      retry_after=response.headers.get('X-Rate-Limit-Reset'))
    twython.exceptions.TwythonAuthError: Twitter API returned a 401 (Unauthorized), Invalid or expired token.

Any help would be appreciated.
