### ISSUE TITLE
twitter.cursor(twitter.search, since_id='some id', q='your_query') return duplicated results

### ISSUE THREAD

**Issue by weasteam** [ryanmcgrath/twython#325]
for result in twitter.cursor(twitter.search,q = "embomolmed.embopress.org",since_id='467233427826434048',result_type="mixed",count=100):
    count += 1
    print "----------------------"
    print count
    print result["id"]
    print result["created_at"]
    print result["text"]
    if count % 100 == 0:
        print count

The code display the tweet 468418418199494656 and 467233427826434048 endlessly.

However, the same code for the tweepy works, only one 468418418199494656 was displayed.

**Comment by JordanRickmanUCI** [comment]
I had the same problem, and tracked it down to the usage of `since_id` instead of `max_id` in the `cursor` method, as @jam1123 described. I didn't want to deal with trying to fix the cursor method, so I'm just paginating manually using the `search` method and passing `max_id` as a parameter.

**Comment by reutsharabani** [comment]
Ran into the same problem.
