### ISSUE TITLE
SSL - Add certificate validation

### ISSUE THREAD

**Issue by alex-fernandez** [ryanmcgrath/twython#355]
Is there a way to  add a certificate to validate the twitter certificate?

**Comment by michaelhelmick** [comment]
http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

`Twython` uses `requests`, you can achieve this by passing `client_args` to the `Twython` object.

`Twython(APP_KEY, APP_SECRET, client_args={'cert': ('/path/server.crt', '/path/key')}`

**Comment by aqm1152** [comment]
where do I find the server.crt and path/key on a mac?
