### ISSUE TITLE
Collecting tweets from 03-20 Aug, 2014 for a particular location

### ISSUE THREAD

**Issue by hasanuzzamanucbn** [ryanmcgrath/twython#369]
Hello,

I am a PhD student. I am new to python and using TwitterSearch to collect tweets from 03-20 Aug for a particular location (geocode). I am trying to run the following piece of code. 

twitter = Twython(CONSUMER_KEY,CONSUMER_SECRET,ACCESS_KEY,ACCESS_SECRET)
results = twitter.cursor(twitter.search, q='ferguson', max_id='501488707195924481', count=100, geocode='38.00,-91.00')

for result in results:
    print (result['id_str'])

However, it is not returning anything. Please help me in this regard. Can I collect old tweets without any keyword for a particular location?

Thanks in advance.

Regards,
Mohammed

**Comment by michaelhelmick** [comment]
Hi @hasanuzzamanucbn 

It looks like you need to specify a radius in your `geocode` parameter as well (according to https://dev.twitter.com/rest/reference/get/search/tweets)

```python
results = twitter.cursor(twitter.search, q='ferguson', max_id='501488707195924481', count=100, geocode='38.00,-91.00,1mi')
```

That would get all tweets matching that query, in a 1 mile radius of 38.00,-91.00

**Comment by mandarvaze** [comment]
@hasanuzzamanucbn Should this issue be closed ? 
After @michaelhelmick 's suggestion, there doesn't seem to be any "next action" to close this issue.
