### ISSUE TITLE
No support for x_auth_access_type with get_authentication_tokens method?

### ISSUE THREAD

**Issue by TristanH** [ryanmcgrath/twython#371]
See https://dev.twitter.com/oauth/reference/post/oauth/request_token

The x_auth_access_type header is used when you want your app to be able to read-write in some cases and only read in others, and there's no way to set it right now, unless I'm mistaken?

Thanks!

**Comment by michaelhelmick** [comment]
I made a new branch `bugs/371`. I added a new method `Twython.obtain_request_tokens`, parameters are `oauth_callback` which is required, and the optional `x_auth_access_type`.

Let me know if this works how you expected, sorry for such a late response!

**Comment by TristanH** [comment]
Sorry for a much later response. I haven't gotten a chance to test this as I'm not using twitter API anymore, but thanks for this fix!
