### ISSUE TITLE
Unable to see docs nor examples for upload_media

### ISSUE THREAD

**Issue by Oire** [ryanmcgrath/twython#375]
I would like to add a possibility to upload media to my [client](https://github.com/Oire/theqube).  
In the `endpoints.py` I saw that the docs are [here](        https://dev.twitter.com/rest/public/uploading-media-multiple-photos). But it says "Access denied" and there is no example in the `examples` folder.  
Please help.  
Thanks!

**Comment by michaelhelmick** [comment]
Hello,

That API method is removed from Twitter.

You'll need to upload the media, https://github.com/ryanmcgrath/twython/blob/master/twython/endpoints.py#L132-L140 (https://dev.twitter.com/rest/reference/post/media/upload)

And then update status with the `media_ids` from the media upload response.

**Comment by Oire** [comment]
@michaelhelmick, OK, thanks. So the issue now is that there is incorrect URL in the docs (see the lines you pointed me to in `endpoints.py`) and there is no example :)

**Comment by michaelhelmick** [comment]
Feel free to make a pull request changing the url to the one I sent in the comment! :)
