### ISSUE TITLE
Access denied Topif of Developer Interface

### ISSUE THREAD

**Issue by lzanuz** [ryanmcgrath/twython#377]
Hi,

I don't know if this is the right place for that but I'd like to say that this URL in documentation gives response:

Access denied
You are not authorized to access this page. 

https://dev.twitter.com/rest/public/uploading-media-multiple-photos

Thanks,

**Comment by Oire** [comment]
This was reported by me in #375 and addressed in #376 which is already merged by @MichaelHelmick. There is another URL for this now.

**Comment by lzanuz** [comment]
OK Oire, thanks for your answer.
