### ISSUE TITLE
How do I make Twython play nicer with Python to Exe programs?

### ISSUE THREAD

**Issue by uncle-scooter** [ryanmcgrath/twython#378]
I've made a program with Twython as the framework for accessing the Twitter Api. It works fine when ran as a python program, but after compiling it with py2exe, pyinstaller, and cxfreeze, it returns the same error:

```
File "twython\endpoints.pyc", line 169, in search
File "twython\api.pyc", line 263, in get
File "twython\api.pyc", line 257, in request
File "twython\api.pyc", line 165, in _request
twython.exceptions.TwythonError: [Errno 2] No such file or directory
```

I've made sure to include twython.exceptions when compiling. I cannot seem to get this thing to work properly as an executable. I've attempted on my computer and a fresh VM so there shouldn't be any installation issues. Any ideas?

**Comment by michaelhelmick** [comment]
Hi, I'm not too familiar with Windows development -- but I can try and help.

Is your root folder named `twython`? It may be trying to import from the wrong directory.
