### ISSUE TITLE
Video upload fails on APPEND command

### ISSUE THREAD

**Issue by ping** [ryanmcgrath/twython#380]
Twitter has opened up video uploads through the REST API. The process varies from the image upload process and requires three steps to upload the video file https://dev.twitter.com/rest/public/uploading-media#chunkedupload

Twython throws a json encode error during the "APPEND" command because Twitter returns an empty response body on successful upload. I was able to work around this by ignoring the error and continue on to the FINALIZE step to complete the upload. This is not ideal though and Twython will need to handle this properly.

**Comment by akarambir** [comment]
@ping I have submitted a PR regarding this and it has been merged. You can try master branch and see if it suits your needs.

**Comment by ping** [comment]
Looks good. Thanks for the fix.

**Comment by michaelhelmick** [comment]
@ping did @akarambir PR end up fixing this issue, you can test it in Twython 3.4.0?
