### ISSUE TITLE
get_authentication_tokens - oauth_callback sent incorrecty

### ISSUE THREAD

**Issue by jvanasco** [ryanmcgrath/twython#387]
get_authentication_tokens sends the callback in as a query arg

it just-so-happens to work on the Twitter API right now, but shouldn't.

I realized this when setting up a stand-in twitter endpoint for integrated tests.  This breaks oauthlib's provider (which requires all oauth_ params to be sent via a unified location).

The Twitter API reinforces this:

"If you’re using HTTP-header based OAuth, you shouldn’t include oauth_\* parameters in the POST body or querystring." [https://dev.twitter.com/oauth/reference/post/oauth/request_token]

So this works now, but shouldn't work.  The oauth_callback should be placed in the header.

**Comment by jvanasco** [comment]
technically speaking, the oauth_verifier in get_authorized_tokens should be in the header as well.  I don't know if twitter accepts it in the header or just the url.  it's worth noting now though, because twitter can change.

**Comment by michaelhelmick** [comment]
@jvanasco Thanks! So basically, if the time comes; we'd need to remove the `oauth_` params from the POST body and strictly send them in the headers?

**Comment by jvanasco** [comment]
Yeah.  But the callback as a param in `get_authentication_tokens` should definitely be removed ASAP -- it's directly going against their docs and shouldn't work -- it just happens to work.  The 'better' fix would be to remove it from that function, and pass it into the oauth constructor on __init__.  The 'it works!' way is to replace the existing callback function in the oauth session, make the call, then switch things back again if needed.  They could potentially fix this without any warning.

The oauth_verifier in `get_authorized_tokens ` is specified as a param.  It seems to break the oauth spec, but Twitter is requesting it like that -- so I don't think it's likely to change without warning.

**Comment by ryanmcgrath** [comment]
So... I know this is from 2015, but I glanced at it while clearing out this almost decade-long backlog.

This seems to me like it _should_ be an issue, but clearly still works... and I can't find relevant docs on Twitter's side to indicate otherwise. I'm guessing it's legacy and left in as such at this point so I'm reluctant to change it now.

Going to close this, assuming it will blow up if it ever needs to be in the header.
