### ISSUE TITLE
Concurrent request for faster process

### ISSUE THREAD

**Issue by vionemc** [ryanmcgrath/twython#394]
Hi,

Is it possible for twython to support concurrent request to Twitter API? I am intending to get the data faster and in bulk.

If I should make the patch on my own, maybe you can give me some hint.

Thanks

**Comment by michaelhelmick** [comment]
This isn't really possible without something like `grequests` or something that can fetch multiple requests and return them either in order or async. A custom solution might fit best.

I don't think we'll implement this in Twython, but if you do do it -- feel free to share your code example here and I'll add it to our `examples` folder.
