### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by fluffy-critter** [ryanmcgrath/twython#395]
The current Twython docs can be pretty hard to read because it's one giant alphabetized list. It would be nice if the various endpoints were grouped together into functional suites (similar to the Twitter API docs) and then pulled in as a Mixin or the like.

It would also be beneficial to provide a documentation section that provides HOWTO-type stuff, and/or some sample simple client applications (such as a command line Twitter client that demonstrates OOB login, watching a timeline, and posting tweets).

I did eventually figure out enough to make a simple CLI OAuth verifier and a chatbot (see https://github.com/plaidfluff/fluff_ebooks) and perhaps that could be helpful for someone else.

**Comment by ryanmcgrath** [comment]
This issue, while old, had the right idea. I don't have time to do it but it's something people are always welcome to pull request.
