### ISSUE TITLE
Favoriting a tweet from a protected account.

### ISSUE THREAD

**Issue by harisibrahimkv** [ryanmcgrath/twython#401]
I was using Twython's create_favorite API to favorite this tweet: https://twitter.com/nstlbcn/status/638052630506377217 (Protected account)

That tweet is apparently a retweet of https://twitter.com/77MASH/status/637689927287894016.

The API throws the following error:

```
inst.create_favorite(id=tweet_id)
TwythonError: Twitter API returned a 404 (Not Found), No status found with that ID.
```

However, the original tweets ends up being favorited anyway even though Twython raised an exception. Isn't this inconsistent? Or do you think our application should handle the logic (haven't thought what it would be yet).

**Comment by harisibrahimkv** [comment]
Actually, the funny thing is, if I try t favourite that protected tweet again, it says `TwythonError: Twitter API returned a 403 (Forbidden), You have already favorited this status.`

**Comment by michaelhelmick** [comment]
Hm, do you have any experience with using the `requests` library? Maybe try to make the call straight through there, although... Twython wraps that library and handles whatever status code is returned. It may be a hiccup in Twitter's API. Have you tried unfavoriting it and then favoriting it again?

**Comment by ryanmcgrath** [comment]
Whatever this was, it's years old and sounds like a bug in Twitter's API at the time. Closing.
