### ISSUE TITLE
Deal with Twitter API returned a 403 (Forbidden) error in api.py

### ISSUE THREAD

**Issue by algarecu** [ryanmcgrath/twython#402]
Do you guys have any way to deal with this error in the API layer? It does not seem so. If not, I think it should be implemented.
Twitter API returned a 403 (Forbidden), User has been suspended.

Traceback (most recent call last):
  File "./id-show.py", line 14, in <module>
    data = twitter.show_user(user_id=target)
  File "build/bdist.macosx-10.3-fat/egg/twython/endpoints.py", line 426, in show_user
  File "build/bdist.macosx-10.3-fat/egg/twython/api.py", line 230, in get
  File "build/bdist.macosx-10.3-fat/egg/twython/api.py", line 224, in request
  File "build/bdist.macosx-10.3-fat/egg/twython/api.py", line 194, in _request
twython.exceptions.TwythonError: Twitter API returned a 403 (Forbidden), User has been suspended.

Since this is not a hard-failure, what one would want is *not* to retry for sure, as in:

line 195 of api.py:
raise ExceptionType(
                error_message,
                error_code=response.status_code,
                retry_after=response.headers.get('X-Rate-Limit-Reset’))

**Comment by algarecu** [comment]
Closed, just dealt with it by writting a custom function that reads error code returned and then returns itself to the main loop of the program in order to continue it execution.

**Comment by michaelhelmick** [comment]
@algarecu FWIW you can do something like this.

```python
twitter = Twython(...)
try:
    data = twitter.show_user(user_id=target)
except TwythonError, e:
    if e.error_code == 403:
        pass // handle however you want to...
```
