### ISSUE TITLE
ImportError: cannot import name is_secure_transport

### ISSUE THREAD

**Issue by evamy** [ryanmcgrath/twython#406]
I've been busy with this the past few days. I googled, to find solutions related to upgrading the oauthlib to the latest version.

My oauthlib and twython as well seem to have been upgraded but I still am not able to find a solution to this problem. I tried to look for things in twython but did not get anywhere with it. Please help me.

**Comment by michaelhelmick** [comment]
In your environment, can you run "pip freeze" and comment with the results?


--

Sent with Airmail

**Comment by evamy** [comment]
PAM==0.4.2
Pillow==2.3.0
Twisted-Core==13.2.0
Twisted-Web==13.2.0
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
argparse==1.2.1
beautifulsoup4==4.2.1
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
compizconfig-python==0.9.11.3
cvxopt==1.1.4
debtagshw==0.1
decorator==3.4.0
defer==1.0.6
dirspec==13.10
duplicity==0.6.23
html5lib==0.999
httplib2==0.8
ipython==4.0.0
ipython-genutils==0.1.0
joblib==0.7.1
lockfile==0.8
lxml==3.3.3
matplotlib==1.3.1
mcomix==1.01
nose==1.3.1
numexpr==2.2.2
numpy==1.8.2
oauthlib==0.6.1
oneconf==0.3.7.14.04.1
openpyxl==1.7.0
pandas==0.13.1
path.py==8.1.2
patsy==0.2.1
pexpect==3.1
pickleshare==0.5
piston-mini-client==0.7.5
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pygobject==3.12.0
pyparsing==2.0.1
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5ubuntu2
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
pytz==2012c
pyxdg==0.25
reportlab==3.0
requests==2.2.1
requests-oauthlib==0.6.0
scipy==0.13.3
sessioninstaller==0.0.0
simplegeneric==0.8.1
simplejson==3.3.1
six==1.5.2
software-center-aptd-plugins==0.0.0
statsmodels==0.5.0
system-service==0.1.6
tables==3.1.1
traitlets==4.0.0
twython==3.3.0
ubuntu-tweak==0.8.8
unity-lens-photos==1.0
urllib3==1.7.1
virtualenv==1.11.4
wheel==0.24.0
wsgiref==0.1.2
xdiagnose==3.6.3build2
xlrd==0.9.2
xlwt==0.7.5
zope.interface==4.0.5

That's what I got on "pip freeze"

I saw the oauthlib and requests which was outdated, so I updated those again, but the output of "pip freeze" remains the same.

**Comment by michaelhelmick** [comment]
Can you try and upgrade requests? `pip install -I requests` that's an "eye"

**Comment by evamy** [comment]
No, didn't work, still the same

**Comment by michaelhelmick** [comment]
Hm, can you also try to do the same for `requests-oauthlib`? `pip install -I requests-oauthlib==0.4.1`

I don't think we updated to support anything past that version yet. 

Upgrading to that should install a different oauthlib as well... I haven't done a whole lot of testing in Twython recently, so this env is kind of old; but here is mine:

```
PyYAML==3.11
argparse==1.2.1
cov-core==1.14.0
coverage==3.6
mock==1.0.1
nose==1.3.4
nose-cov==1.6
oauthlib==0.7.1
python-coveralls==2.1.0
requests==2.1.0
requests-oauthlib==0.4.0
responses==0.3.0
sh==1.09
six==1.8.0
wsgiref==0.1.2
```

**Comment by evamy** [comment]
I did as you suggested. But the results were not good.

But, I do seem to have found the problem, pip is installing the requests and others in different folders(I have no idea why and how). Here is a piece of what I am trying to say :

   evamy@Antriksh-Agarwal ~/UserClassify> python -c "from pkg_resources import Environment;print(Environment()['requests'])"
   [requests 2.9.1 (/usr/local/lib/python2.7/dist-packages), requests 2.2.1 (/usr/lib/python2.7/dist-packages), requests 2.1.0 (/usr/local/lib/python2.7/dist-packages)]

**Comment by evamy** [comment]
Actually, solved it, thanks anyways for your help !

**Comment by liulong07525046** [comment]
i have met this kind of problem  want help
/usr/local/lib/python2.7/dist-packages/Mezzanine-4.2.2-py2.7.egg/mezzanine/utils/conf.py:61: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.12-py2.7.egg/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.12-py2.7.egg/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.12-py2.7.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.12-py2.7.egg/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.12-py2.7.egg/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/Mezzanine-4.2.2-py2.7.egg/mezzanine/twitter/models.py", line 18, in <module>
    from requests_oauthlib import OAuth1
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib-0.8.0-py2.7.egg/requests_oauthlib/__init__.py", line 3, in <module>
    from .oauth2_auth import OAuth2
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib-0.8.0-py2.7.egg/requests_oauthlib/oauth2_auth.py", line 3, in <module>
    from oauthlib.oauth2 import is_secure_transport

**Comment by liulong07525046** [comment]
how to solve this proble  ?
