### ISSUE TITLE
Twitter API returned a 401 (Unauthorized), This request is not properly authenticated

### ISSUE THREAD

**Issue by johendry** [ryanmcgrath/twython#407]
My code:
from twython import Twython

APP_KEY = 'my app_key'
APP_SECRET ='my app_secret_key'

OAUTH_TOKEN = auth['oauth_token']
OAUTH_TOKEN_SECRET = auth['oauth_token_secret']

twitter = Twython(APP_KEY, APP_SECRET)
auth = twitter.get_authentication_tokens(callback_url='http://www.mysite.com/callback')
twitter = Twython(OAUTH_TOKEN)

twitter.request('https://ads-api.twitter.com/0/accounts/myaccountid/campaigns')

and got error like this
Twitter API returned a 401 (Unauthorized), This request is not properly authenticated

what should i do?

**Comment by michaelhelmick** [comment]
#403 adds support for the Twitter Ads API. It will be merged and a release will be cut by the end of the month. Sorry for the wait, just have been really busy.
