### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by waveform80** [ryanmcgrath/twython#410]
Any chance you could build back-level versions of your docs on RTD? I'm not bothered if the default build stays as "latest" but it'd be really handy if older versions of the docs could be easily retrieved.

Some background: we recently had some interesting times with the teachers at picademy trying to use Twython in their projects, specifically for tweeting images. The version packaged in Raspbian is 3.1 (not the latest, but then that's pretty par for the course on stable distros) and unfortunately the [example given in the docs](http://twython.readthedocs.org/en/latest/usage/advanced_usage.html#updating-status-with-image) won't work with 3.1 (as it relies on `upload_media` which was introduced after 3.1).

**Comment by michaelhelmick** [comment]
I can probably check the project out at that version release and build the docs for that version? I'm not sure how great that would work. But I could def. give it a try. Or at the very least, link you to the example in 3.1?


--

Sent with Airmail

**Comment by waveform80** [comment]
No need for you to check out stuff or do manual builds: it's pretty easy under RTD, but it does assume you're tagging your releases (and I've just noticed, looking at the Twython github repo that [only 3.3.0 has a tag](https://github.com/ryanmcgrath/twython/tags)). So: tag your releases, then under RTD's admin page for your project you should find those tags start showing up under the "Versions" section (you might have to do `git push --tags` for that to happen).

Once they've shown up there, just set the tags you want to "Active" and they'll become available as versions of your docs (on my projects I usually set the last release as the "Default Version" rather than "latest" so that I can continue hacking on stuff without confusing people using the released version - but plenty of projects stick with "latest" as the default version, presumably under the assumption that many of their users are bleeding edge `pip` installs).

**Comment by michaelhelmick** [comment]
Alright, I think I got it. I started tagging actually with the 3.3.0 release. So we'll be tagging releases and making them available on RTD in the future.

Hope this helps! http://twython.readthedocs.org/en/3.1.2/usage/advanced_usage.html
