### ISSUE TITLE
Can't get latest version of v3.3.0 from pypi

### ISSUE THREAD

**Issue by philgyford** [ryanmcgrath/twython#414]
If I install twython with pip or my project's setup.py, it *says* it's v3.3.0 but I've noticed it doesn't include a particular commit I'm interested in (2ea45abb734af5a3de1e89a4ed2ea1a63e482160).

But if I download the zip of v3.3.0 from GitHub's tags/releases page, I get a version that *does* include that commit.

I guess this is because the v3.3.0 [on pypi](https://pypi.python.org/pypi/twython) was uploaded on 2015-07-18, while the v3.3.0 [on GitHub](https://github.com/ryanmcgrath/twython/releases/tag/3.3.0) is from 2016-03-21.

Am I missing something - I'm far from a python guru - or is this not right?

**Comment by vaheder** [comment]
Similar issue here. upload_video is not available in endpoints.py on the pypi version of 3.3.0.

**Comment by michaelhelmick** [comment]
Hi, sorry for the delay in any release. Work and personal life are getting crazy.

In any matter, 3.3.0 didn't include the video endpoint.

3.3.0 was tagged on GitHub for convenience (requested by another user I believe) but the last commit in that tag was https://github.com/ryanmcgrath/twython/commit/885051acdc00ba5a67f986ed9ab8d6ae42fd77ac (before new upload video endpoint)

I can do a quick 3.4.0 release with that endpoint and then over the next couple weeks I'll have a look at your other pull requests and get those merged in!

**Comment by michaelhelmick** [comment]
Twython 3.4.0 should be available and should include the `upload_video` endpoint. Sorry about the confusion!

**Comment by vaheder** [comment]
Thanks very much for moving so quickly on this, Mike!
