### ISSUE TITLE
upload_video: 'string argument detected, got 'bytes'

### ISSUE THREAD

**Issue by choiRyan** [ryanmcgrath/twython#422]
I first tried the following on Python 3.4 and Twython 3.4:

`video = open(tempfile_name, 'rb')`
`response = twitter.upload_video(media=video, media_type='video/mp4')`

and received an error:
`media_chunk.write(data)`
`TypeError: string argument expected, got 'bytes'`

I think using StringIO in Python3 instead of BytesIO in `upload_video` in `endpoints.py` led to this issue; on endpoints.py I changed the python3 import `from io import StringIO` (i.e. if StringIO.StringIO not found) to `from io import BytesIO` and `upload_video` now works with my last attempt (with the tempfile).

**Comment by eliorkilometer** [comment]
Following [twython video upload docs](https://twython.readthedocs.io/en/latest/usage/advanced_usage.html#updating-status-with-video) still results in `TypeError: string argument expected, got 'bytes'`

Any valid way to upload a post with video via Twython?
