### ISSUE TITLE
Images in some Tweets aren't appearing in the tweet data

### ISSUE THREAD

**Issue by kesterallen** [ryanmcgrath/twython#430]
I ran across a tweet today for which the Twython.show_status dict doesn't contain the URL for the image in the tweet. Previously I've checked the tweet dict for 'entities' or 'extended_entities' (the latter being a set of images), but this isn't working for this tweet. Not sure what's going on.

```
from twython import Twython

# Contains an image
url = 'https://twitter.com/joshharrison_2/status/779143860006125568'
tweet_id = url.split('/')[-1]

twitter = Twython(APP_KEY, APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET)
tweet = twitter.show_status(id=tweet_id)

if 'extended_entities' in tweet:
    entities = tweet['extended_entities']
elif 'entities' in tweet:
    entities = tweet['entities']
    
urls = []
if 'media' in entities:
    medias = entities['media']
    for media in medias:
        url = media['media_url']
        urls.append(url)

```

**Comment by ping** [comment]
https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

That tweet has ``"truncated": true`` which is an indication that the tweet has > 140 chars.

You need to specify tweet_mode ``tweet = twitter.show_status(id=tweet_id, tweet_mode='extended')`` to get the full tweet payload and if you're using the tweet ``text`` field originally, you must now switch to using the ``full_text``, example: ``tweet_text = tweet.get('full_text') or tweet['text']``.

**Comment by kesterallen** [comment]
Ah, that's great. Thank you! Really appreciate it.

**Comment by kesterallen** [comment]
The previous comment resolved my issue.
