### ISSUE TITLE
Is it possible to do >15MB video uploads, async, using upload_video()?

### ISSUE THREAD

**Issue by philgyford** [ryanmcgrath/twython#432]
I want to upload videos to Twitter that are larger than 15MB, which is only possible using "async".

Twython's [upload_video()](https://github.com/ryanmcgrath/twython/blob/master/twython/endpoints.py#L153) method says it only supports up to 15MB, but it _looks_ like it can maybe do async uploads, using the `check_progress` parameter?

But this isn't documented in the comments or the documentation, so I'm not sure (a) how to use that, (b) if that is actually for doing async uploads, and (c) if it will allow the uploading of >15MB videos.

**Comment by michaelhelmick** [comment]
Do either of these pull requests help?

https://github.com/ryanmcgrath/twython/pull/396/files
https://github.com/ryanmcgrath/twython/pull/428/files

The last one might be more helpful, as check_progress was implemented.

**Comment by philgyford** [comment]
Thanks, although I'm still not quite sure how to use it. I've tried:

    response = twitter.upload_video(media=my_video, media_type='video/mp4', check_progress=True)

but with a large (26MB) video still get this, just as if I don't use `check_progress`:

> twython.exceptions.TwythonError: Twitter API returned a 400 (Bad Request), An error occurred processing your request.

I assume that's due to the size. I don't get the error with smaller videos (without `check_progress`).

I feel like I'm missing something obvious, sorry.

**Comment by thisisparker** [comment]
Hi @philgyford:

I know it's a fair bit later, but I ran into this issue and only solved my problem after, so I'm going to answer here in the hopes that it's helpful to you or somebody else. If you haven't gotten it working yet, and if you're using Twython 3.5.0, I'd add a 'media_category' to your request. So in this case it would look like:

<pre>response = twitter.upload_video(media=my_video, media_type='video/mp4', media_category='tweet_video', check_progress=True)</pre>

Twitter's documentation on this is really fuzzy, but I found that explicitly including the category was enough to make it work on longer videos.

**Comment by philgyford** [comment]
@thisisparker Thanks for this! I'm not updating the project that I was working on at the moment, but if I return to it, or do something similar in future, I'll give this a try. Thanks for the info!

**Comment by TariqMK** [comment]
> Hi @philgyford:
> 
> I know it's a fair bit later, but I ran into this issue and only solved my problem after, so I'm going to answer here in the hopes that it's helpful to you or somebody else. If you haven't gotten it working yet, and if you're using Twython 3.5.0, I'd add a 'media_category' to your request. So in this case it would look like:
> 
> response = twitter.upload_video(media=my_video, media_type='video/mp4', media_category='tweet_video', check_progress=True)
> Twitter's documentation on this is really fuzzy, but I found that explicitly including the category was enough to make it work on longer videos.

@thisisparker Thanks for your reply, I have added the code:

`media_category='tweet_video'`

In the same part of my code as you have, but unfortunately it still doesn't seem to work. 

When I execute my script I get the new error:

**TypeError: upload_video() got an unexpected keyword argument 'media_category'**

I'm confused as to why Twython doesn't understand the 'media_category' tag, any reason why?

**Comment by thisisparker** [comment]
@TariqMK what version of Twython are you using? That parameter hasn't always been there, but has been for at least a few years now. I believe it's only in `3.5.0` and higher.

**Comment by TariqMK** [comment]
@thisisparker 

I see, I only installed Twython maybe 3/4 months ago so I assumed I had the latest version.

Upon checking it seems I have:

`python3-twython/stable,now 3.4.0-1 all`

Using the standard 'sudo apt-get upgrade' doesnt pick up any updates for Twython. Any ideas?

**Comment by thisisparker** [comment]
@TariqMK this is a bit beyond the scope of this issue, but you can get a more recent version than what's in the operating system repos by [using pip or installing from source](https://twython.readthedocs.io/en/latest/usage/install.html). You may want to uninstall the version you got through apt to avoid conflicts.

Forgive me if you know this, but, you can start to run into problems if you're installing modules for your "system" Python, and you can save yourself a lot of headaches by [putting each project in a virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/). There are a bunch of options for that and people are opinionated, but you will probably want to find one that works for you if you haven't yet.
