### ISSUE TITLE
name 'twython' is not defined

### ISSUE THREAD

**Issue by M0nica** [ryanmcgrath/twython#437]
When I run my script locally it works fine...however, when I transferred to a digital ocean server I am no longer able to run my script and get the following error even though I have the most up to date version of twython installed via `pip install twython` and also installed `sudo apt-get install python3-requests-oauthlib` in case that was a dependency

```
twitter = twython.Twython(api_key, api_secret, access_token, token_secret)
NameError: name 'twython' is not defined
```

Here's a copy of the script that I am trying to run https://github.com/M0nica/blackgirlmagic/blob/master/blackgirlmagic_rt.py

I am trying to determine if this is a common error/easily fixable, I was not able to find a solution.

**Comment by ryanmcgrath** [comment]
Just do `Twython(api_key, api_secret, access_token, token_secret)`, since you're importing it already with this `from twython import Twython, TwythonError`.

**Comment by M0nica** [comment]
Thank you @ryanmcgrath. That resolved the issue for me.
