### ISSUE TITLE
Authenticate request for image sent by direct message

### ISSUE THREAD

**Issue by PaulNorton** [ryanmcgrath/twython#439]
Is it possible to use twython to make an authenticated request for an image sent by direct message? This would just be a request to the url of that image with the authentication header. You can use the twython.get() method to request from a specific url but it tries to convert the response to JSON.

**Comment by michaelhelmick** [comment]
Currently, no. Do you have some example code (please don't post app and consumer keys).

I see in api.py that we try to use `content.json()` from the response

**Comment by PaulNorton** [comment]
I figured out a way to get it working!

```
from twython import *
twitter = Twython(APP_KEY, APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET)
image = twitter.client.get(URL)
```

Using the Twython client allows the request to be authorized with the Twitter OAuth.
