### ISSUE TITLE
Upgrading from twython 2.8.0

### ISSUE THREAD

**Issue by anentropic** [ryanmcgrath/twython#441]
Hi,

I'm just auditing the dependencies in one of my projects.

It currently has `twython==2.8.0` and that version requires `requests==1.2.0` which is pretty old

Question:  are you aware of any breaking changes between 2.8.0 to current 3.4.0 of Twython?

Apologies if there's a changelog detailing this somewhere that I haven't found

**Comment by michaelhelmick** [comment]
Most of the changes happened in 3.0.0 that would break any backwards compat. 

https://github.com/ryanmcgrath/twython/blob/master/HISTORY.rst#L61

If you have any questions on your quest of upgrading feel free to ask in this issue! I'll try to help to the best of my ability

**Comment by anentropic** [comment]
oh, just found a pretty good changelist here too https://pypi.python.org/pypi/twython :)

thanks

**Comment by michaelhelmick** [comment]
Oh yep. That works too!

**Comment by anentropic** [comment]
typically it's probably used in a part of my project with poor test coverage... sigh

anyway, thanks
