### ISSUE TITLE
Python3 not updated to use BytesIO in endpoints.py

### ISSUE THREAD

**Issue by ekhaydarov** [ryanmcgrath/twython#442]
The simple import fix that was merged is not reflected in python3 version for some reason?

import is still looking like

```
import os
import warnings
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
```

is it simple enough to port it to python 3?

**Comment by michaelhelmick** [comment]
This should now be fixed in Twython 3.5.0
