### ISSUE TITLE
get_user_timeline does not retreive the complete text from tweet

### ISSUE THREAD

**Issue by farzadsamie** [ryanmcgrath/twython#443]
I'm using a simple script to retrieve tweets from a timeline. These tweets are not in English, they have non-English alphabets.
This is [the script](https://github.com/hypnoJerk/from_twitter_to_telegram) that I'm using. 

It uses the Twython api to get_user_timeline. I parse and show the 'text' object from each entry. But the text is not complete! If the tweet is long, I don't receive the whole text. It misses a few last characters. 
I also checked the 'retweeted_status', it's text is not complete either.

For example, the only text that I get from  [this tweet](https://twitter.com/FcEsteghlal/status/867123535814307841) in unicode is: 
`RT @FcEsteghlal: \u062e\u06cc\u0644\u06cc \u0627\u0647\u0644 \u0634\u0639\u0627\u0631 \u062f\u0627\u062f\u0646 \u062f\u0631 \u0645\u0648\u0631\u062f \u0645\u0646\u0627\u0641\u0639 \u0645\u0644\u06cc \u0646\u06cc\u0633\u062a\u06cc\u0645\u060c\n\u06a9\u0627\u0648\u0647\u200c \u0646\u0634\u0648\u0646 \u062f\u0627\u062f \u0686\u0631\u0627 \u0628\u0647\u062a\u0631\u06cc\u0646 \u0645\u0647\u0627\u062c\u0645 \u0627\u06cc\u0631\u0627\u0646 \u0647\u0633\u062a\u0634\u060c\n\u0645\u0631\u0633\u06cc \u06a9\u0647 #\u067e\u0646\u0627\u0644\u062a\u06cc \u0632\u062f\u0646 \u0628\u0644\u062f\u06cc\n#\u0627\u0633\u062a\u0642\u0644\u0627\u0644\u2026`

However, the entire message should be like this:
`\u062e\u06cc\u0644\u06cc \u0627\u0647\u0644 \u0634\u0639\u0627\u0631 \u062f\u0627\u062f\u0646 \u062f\u0631 \u0645\u0648\u0631\u062f \u0645\u0646\u0627\u0641\u0639 \u0645\u0644\u06cc \u0646\u06cc\u0633\u062a\u06cc\u0645\u060c \u06a9\u0627\u0648\u0647\u200c \u0646\u0634\u0648\u0646 \u062f\u0627\u062f \u0686\u0631\u0627 \u0628\u0647\u062a\u0631\u06cc\u0646 \u0645\u0647\u0627\u062c\u0645 \u0627\u06cc\u0631\u0627\u0646 \u0647\u0633\u062a\u0634\u060c \u0645\u0631\u0633\u06cc \u06a9\u0647 \u0023\u067e\u0646\u0627\u0644\u062a\u06cc \u0632\u062f\u0646 \u0628\u0644\u062f\u06cc \u0023\u0627\u0633\u062a\u0642\u0644\u0627\u0644 \u0023\u0631\u0636\u0627\u06cc\u06cc \u0023\u0622\u0633\u06cc\u0627`

This part is missing: `\u0023\u0631\u0636\u0627\u06cc\u06cc \u0023\u0622\u0633\u06cc\u0627` which corresponds to:  `#رضایی #آسیا`

**Comment by eliasdabbas** [comment]
@farzadsamie 
You need to add the `tweet_mode='extended'` parameter, and you should get the full text. 
In this case the key in the response will be `full_text` and not `text`

for example:
`user_timeline = api.get_user_timeline(screen_name=user_name, count=2, tweet_mode='extended')`
