### ISSUE TITLE
Won't install on Python 3.2 (Raspberry Pi)

### ISSUE THREAD

**Issue by hack-r** [ryanmcgrath/twython#445]
Here's the error I ran into. This is also on StackOverflow. Note I added sudo because I had to.

`sudo pip-3.2 install twython`

> 
> 
> Running setup.py egg_info for package requests
>     Traceback (most recent call last):
>       File "<string>", line 14, in <module>
>       File "/home/pi/twython/build/requests/setup.py", line 52, in <module>
>         exec(f.read(), about)
>       File "<string>", line 14
>         __cake__ = u'\u2728 \U0001f370 \u2728'
>                                              ^
>     SyntaxError: invalid syntax
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
> 
>   File "<string>", line 14, in <module>
> 
>   File "/home/pi/twython/build/requests/setup.py", line 52, in <module>
> 
>     exec(f.read(), about)
> 
>   File "<string>", line 14
> 
>     __cake__ = u'\u2728 \U0001f370 \u2728'
> 
>                                          ^
> 
> SyntaxError: invalid syntax
> 
> ----------------------------------------
> Command python setup.py egg_info failed with error code 1 in /home/pi/twython/build/requests

Next I searched on the last line of the error and followed some suggestions that said to make sure setuptools and ez_install were installed and up to date, but that didn't help.

Then I tried this:

```
git clone git://github.com/ryanmcgrath/twython.git
cd twython
sudo python3 setup.py install
```

> 
> Error in atexit._run_exitfuncs:
> TypeError: 'NoneType' object is not callable

Slightly more info on the error messages here: https://stackoverflow.com/questions/44348484/cant-install-twython-on-python-3-2-raspberry-pi

**Comment by michaelhelmick** [comment]
Hm, it appears to be failing when requests tries to install.

@Lukasa have you seen this behavior?

**Comment by Lukasa** [comment]
The current Requests does not support Python 3.2 and has not done so for some time: at least a year.

**Comment by michaelhelmick** [comment]
Ah, thanks! I'll do some work to get Twython to 3.4-3.6!
