### ISSUE TITLE
Outdated version on PyPI

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [ryanmcgrath/twython#449]
Hello dear friend,

Thanks for your awesome work, however the version here on github is ahead than the one on PyPI.
Do you think it would possible to send a minor version on PyPI ?

https://pypi.python.org/pypi/twython/json

This json file is shows critical differences (especially for the "classfiers") and it gives us some trouble because uncomplete "classifiers" is reported in your package...
It flags the package as non Python3 compatible and thus we have many issues with our continuous integrations services ...

I would greatly appreciate a little update on PyPI or at least to get a date when you think releasing a minor revision.

I can help you fixing this if you want to and implement an automatic github and PyPI release when you commit a new tag. Would you be interested @ryanmcgrath ?

Thanks for your time,

Best Regards,

Jonathan

**Comment by michaelhelmick** [comment]
Instead of the automatic release, can you update our classifiers to what they should be? Thanks!

**Comment by DEKHTIARJonathan** [comment]
Thanks for your answer @michaelhelmick. I actually do not need to change or modify anything ... The classifiers seems to be just fined : <https://github.com/ryanmcgrath/twython/blob/master/setup.py>

```python
classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Communications :: Chat',
        'Topic :: Internet',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ]
```

However they do not appear on PyPI, and for a simple reason: the package on PyPI is outdated and the classifiers were updated after the last release : 3.5.0  (commit: 574483d87021e8cdd0272e79f9654f1040634153). That's the reason why I was asking for a minor release.

In order to facilitate this process I was proposing myself to automate this deployment process. If you are not interested, I can not do any to help on this and just have to wait for the next release.

Thanks again for your help. I'm closing it, please re-open it if you feel like this case needs more discussion.

**Comment by michaelhelmick** [comment]
Twython 3.6.0 is available with the correct classifiers.

**Comment by DEKHTIARJonathan** [comment]
@michaelhelmick Thanks a lot! Sincere appreciation
