### ISSUE TITLE
update_status(status='d') always fails

### ISSUE THREAD

**Issue by rdlester** [ryanmcgrath/twython#454]
Any attempts to tweet 'd' via Twython fail with:
twython.exceptions.TwythonError: Twitter API returned a 403 (Forbidden), There was an error sending your message: You can't send a direct message without a user!.

"d'" also fails. Tweeting 'dd' or seemingly anything else works fine.

**Comment by rdlester** [comment]
Same thing happens with "d'".

**Comment by michaelhelmick** [comment]
Per https://dev.twitter.com/rest/reference/post/statuses/update

> The text of the status update, typically up to 140 characters. URL encode as necessary. t.co link wrapping may affect character counts. There are some special commands in this field to be aware of. For instance, preceding a message with “D ” or “M ” and following it with a screen name can create a Direct Message to that user if the relationship allows for it. See the ‘enable_dm_commands’ parameter for information on disabling Direct Message creation to allow any text to be created as a Tweet.
