### ISSUE TITLE
Links in Twython docs to Twitter API docs all now broken

### ISSUE THREAD

**Issue by RedactedCode** [ryanmcgrath/twython#455]
Every link in the Twython docs to the Twitter API documentation is now broken, subsequent to a rejig by Twitter of their own documentation.
Gah!

**Comment by clayadavis** [comment]
https://github.com/ryanmcgrath/twython/pull/463

**Comment by RedactedCode** [comment]
thanks very much for your efforts. 
Hadn't searched issues properly b4 posting :(

**Comment by clayadavis** [comment]
It's the opposite -- I hadn't searched the issues before I made a PR. This issue predates the PR :)
