### ISSUE TITLE
DM Not allowed

### ISSUE THREAD

**Issue by stefanstranger** [ryanmcgrath/twython#466]
Hi people,

I've been using twython for quite some time now but lately I get an error message when trying to send a Direct Message to a new Twitter follower.

Twythonerror: Twitter API returned a 403 (Forbidden). There is an error sending your message. DM commands are no longer allowed!

How do I solve this? If this can be solved :-)

/Stefan

**Comment by RorixRebel** [comment]
Can you share the piece of code you are trying to use?
The documentation that is linked to the twitter api is no longer available so a lot of documentation links need to be updated.
