### ISSUE TITLE
280 characters

### ISSUE THREAD

**Issue by pristis** [ryanmcgrath/twython#467]
Hello!

My account already supports 280 symbols from Twitter app and website, but with Twython I'm still getting error "Twitter API returned a 403 (Forbidden), Status is over 140 characters."

Can I use Twython for long tweets?

Thanks!
Martin

**Comment by michaelhelmick** [comment]
It looks like it's not officially supported via the API, yet.

https://twittercommunity.com/t/280-characters/94200/2
