### ISSUE TITLE
Doc hyperlinks not updated according to new Twitter API Update

### ISSUE THREAD

**Issue by gureks** [ryanmcgrath/twython#468]
Reference: Docs link at https://twython.readthedocs.io/en/latest/api.html

**Comment by gureks** [comment]
@ryanmcgrath If this issue is valid and someone is not already working on it, please assign it to me. I would love to work on it.

**Comment by michaelhelmick** [comment]
Have at it @gureks! :)

**Comment by gureks** [comment]
Hey 
I started on it today and found that the URLs are updated in the function docstrings but not on twython.readthedocs.io 
Where are those files?

**Comment by michaelhelmick** [comment]
The master docs have been updated http://twython.readthedocs.io/en/master/usage/advanced_usage.html

when a new release is pushed, I'll build for latest! Sorry about that!
