### ISSUE TITLE
280 characters length

### ISSUE THREAD

**Issue by Keramatfar** [ryanmcgrath/twython#471]
Dear Developer,
What can we do with new tweets' length?

**Comment by reagle** [comment]
I just came looking for documentation on this. Will twython still enforce the 140 limit, or is 280 okay now?

**Comment by Keramatfar** [comment]
I did a search in twitter by twython and it seems that it limits to 140.

**Comment by Keramatfar** [comment]
Do:
(user_timeline = client.search(q='زلزله -filter:retweets', count=100, tweet_mode='extended')

**Comment by leoss** [comment]
@Keramatfar What does that mean?

I would also be very glad to see 280 chars for a tweet.

**Comment by Menelion** [comment]
Twython does not enforce tweet length. I use 280 chars in my app perfectly. However, you do need to set `tweet_mode` to `extended`, as per Twitter documentation.

**Comment by reagle** [comment]
After some testing, 280 doesn't work correctly for me, but [279 does](https://github.com/reagle/thunderdell/blob/master/b.py#L1345) for some weird reason.

**Comment by Keramatfar** [comment]
See here.
https://stackoverflow.com/questions/47391092/twython-with-140-character-limitation-of-twitter
