### ISSUE TITLE
Non complete results

### ISSUE THREAD

**Issue by Keramatfar** [ryanmcgrath/twython#472]
When i use Tweepy to search Tweets it get for me some number much smaller than real results can be seen in search of Twitter itself. I use cursors but it get me for example 122 tweets while there are a lot of tweets in reality. What is the problem?

**Comment by jukkahuhtamaki** [comment]
Overall, Twitter REST API gives only a limited set of tweets compared to what you seen in the Web interface.

In addition, I believe that the limited number of tweets is related to the recent changes in the REST API.  It seems that the Standard plan is very limited in terms of coverage.  For additional information about the plans, please refer to [REST API plans](https://developer.twitter.com/en/docs/tweets/search/overview) or tiers on Twitter developer site.
