### ISSUE TITLE
Asyncio support?

### ISSUE THREAD

**Issue by likewhoa** [ryanmcgrath/twython#475]
Tweepy doesn't support Asyncio so it's blocking and preventing my asyncio applications from integrating it. I was wondering if there is support being worked on for twypthon and asyncio?

**Comment by ekhaydarov** [comment]
have you tried gevent monkey patch? although not ideal and asyncio support would be great

**Comment by likewhoa** [comment]
no I haven't, i'll look into it though. Thanks!

**Comment by ryanmcgrath** [comment]
Going to close this as

- It's coming up on 2 years old
- Async support probably makes sense, but I don't have the time to add it (someone is free to do so and pull request)
- gevent monkey patching was probably the best approach here given the above
