### ISSUE TITLE
access to Twitter's json error response via TwythonError

### ISSUE THREAD

**Issue by bmeyer71** [ryanmcgrath/twython#476]
Is it possible to access the json response from Twitter for error messages?

It would be nice to be able to use the error codes that they provide here https://developer.twitter.com/en/docs/basics/response-codes instead of the text when handling exceptions.

**Comment by michaelhelmick** [comment]
https://github.com/ryanmcgrath/twython/blob/master/twython/exceptions.py#L21

We assign the error code to the `error_code` attribute of the exception if a `TwythonError` or any sub class is thrown.

**Comment by bmeyer71** [comment]
Those appear to only be the HTTP status codes correct?

I was referring to the error codes further down.
For example, for a duplicate tweet, a 403 Forbidden error is thrown, but if you reference the error codes twitter returns a 327 which is specific to a duplicate tweet.
According to the example they provide, that is the code that is returned in their json response.

Is that a possibility?

**Comment by michaelhelmick** [comment]
Ah! Currently, no. Feel free to open up a pull request adding this functionality though!

**Comment by bmeyer71** [comment]
OK. Thank you for getting back to me. I will close for now.
