### ISSUE TITLE
Any chance of a new release on pypi?

### ISSUE THREAD

**Issue by philgyford** [ryanmcgrath/twython#477]
There have been a few changes since 3.6.0 and it'd be nice to have them more available. Many thanks!

**Comment by michaelhelmick** [comment]
I’ll try and get to this soon!

**Comment by philgyford** [comment]
I've just noticed a new bug with the `html_for_tweet()` method which I'm looking into.

I was wondering if twython should use [twitter-text-python](https://github.com/edburnett/twitter-text-python) for this stuff instead of `html_for_tweet()` trying to do it from scratch? I think we can override twitter-text-python's `format_*` methods, so twython could retain some/all of the current `<span class="twython-...">...</span>` HTML it currently generates.

What do you think? twitter-text-python doesn't look perfect - it doesn't conform to twitter-text's tests and hasn't been updated in a while. But it feels that now Tweets are so complicated, twython might be best to concentrate on the API stuff it does so well, and leave the formatting to a module that does only that?

I'm happy to give this a go if you think it's a good move.

**Comment by michaelhelmick** [comment]
I'd be open to maybe making a new repository, `twython-html-tweet` or something (if you can think of something more clever.. haha) and maybe just make that a dependency of twython. If something hasn't been updated in 2 years, I don't think I'd feel comfortable making it a dependency, esp. if it doesn't conform to twitter texts

**Comment by philgyford** [comment]
Yes, good points. I'm surprised there isn't a twitter-text-python that conforms, given all the others. If I find myself with some time (ha!) I'll think more about what we might do. At least we have something that pretty much works at the moment.

**Comment by anentropic** [comment]
and remember to git tag the release when uploading, would be nice to be able to browse eg 3.6.0 version (last tag is 3.4.0)

**Comment by ryanmcgrath** [comment]
's been done twice since this issue, so closing~
