### ISSUE TITLE
"Twython on Crate" link in docs just leads to CrateDB index page

### ISSUE THREAD

**Issue by eloquence** [ryanmcgrath/twython#483]
There's a link to https://crate.io/packages/twython/ on https://twython.readthedocs.io/en/latest/ , but it just redirects to https://crate.io/ .

**Comment by eloquence** [comment]
Also, the GitTip link errors out since GitTip/Gratipay is gone (RIP)

**Comment by michaelhelmick** [comment]
Hi! Feel free to open up a PR to remove these links, thanks!

**Comment by ryanmcgrath** [comment]
Eh I'm removing them.
