### ISSUE TITLE
Streaming - unable to use multiple "follow=" in stream.statuses.filter()

### ISSUE THREAD

**Issue by RedactedCode** [ryanmcgrath/twython#484]
If I read and understand the Twitter API docs [(here)](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) 
correctly, the statuses./filter endpoint parameters should allow multiple userids, in a comma-separated list.

If I set up a streamer using Python3.5/Twython3.6, and call the filter as follows:
``
stream.statuses.filter(follow=25073877)
``
I get data flowing in as expected.

If however do this:
``
stream.statuses.filter(follow=25073877, 15833737)
``
I get
>  stream.statuses.filter(follow=25073877, 15833737)
>                                                                                 ^
> SyntaxError: positional argument follows keyword argument

I've tried using parentheses and quotes (eg (25073877, 15833737) and '25073877, 15833737') , but then I just get a 406 back complaining about malformed requests.

Twython problem or Twitter problem? Or a me problem because I've misunderstood the docs?

(By the way, is Twython going to be updated to reflect the replacement for the user and site streaming endpoints with Twitter webhooks API? These two are going to be switched off in June/July, and there are also plans to rejig the filter & sample endpoints ...)

**Comment by michaelhelmick** [comment]
It should be fixed if you send a list follow=[25073877, 15833737]

Your code, python is reading the keyword argument follow as the 250... value and the 158... value as an argument (not a keyword argument) and you can’t pass args after kwargs in python.

**Comment by RedactedCode** [comment]
Ah of course the thing I didn't try!
