### ISSUE TITLE
GET user and GET site APIs don't have deprecation warnings

### ISSUE THREAD

**Issue by AN3223** [ryanmcgrath/twython#486]
GET user and GET site have been deprecated and plan to be sunset by Twitter Tuesday June 19, 2018, read more [here ](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/site-stream)and [here](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/user-stream)

**Comment by andremann** [comment]
+1
