### ISSUE TITLE
direct message API obselete

### ISSUE THREAD

**Issue by rjallbert** [ryanmcgrath/twython#496]
The direct message API is now 

direct_messages/events/list

the old one returns a 404.

locally, I took a zip of this repo and modified the code on line 306 in endpoints.py to:
        return self.get('direct_messages/events/list', params=params)

I'm not sure if I should clone this repo, make a branch and pull request?

**Comment by manuelcortez** [comment]
Just in case you are interested in adding post methods to the new direct messages endpoint, take into account Twitter expects it to send json encoded data, so we'd need to pass json=true to requests. I have taken Twython 3.6 for [My Twitter client](https://github.com/manuelcortez/twblue) and modified it so it'll work. I'd send a pr, but still need to update my local modified version of Twython to 3.7, and still need to implement the delete method (For deleting dms twitter wants a delete requests, as opposed to the post one we were using previously).

**Comment by jvmaia** [comment]
I sent a pull request updating the endpoints and adding a function to return the direct messages (get/list) in the old format (WIP); that way the clients don't have to be updated;
