### ISSUE TITLE
send_direct_message does not work anymore

### ISSUE THREAD

**Issue by parikshitsharma70** [ryanmcgrath/twython#501]
Since twitter has changed the way the Direct Message API works on September 18th, all the functions related to direct messages in this module have turned obsolete.

I managed to get a hold of the new get_direct_message function from this fork : https://github.com/jvmaia/twython

But the send_direct_message behaviour has changed completely. It now requires:

type: 'message_create'

message_create.target.recipient_id: 'xxx'

message_create.message_data: 'xxx'

Would be very grateful if someone could help me change the POST request according to the sample post request which is provided on the Twitter Documentation [here](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event)

**Comment by Menelion** [comment]
Please see #500. @michaelhelmick haven't answered so far, unfortunately.

**Comment by parikshitsharma70** [comment]
I got it to work by hard-coding the POST request and creating a new def post_message in the api.py

Here is the code for your reference:

```
def post_message(self, endpoint, params=None, version='1.1', json_encoded=False):
        """Shortcut for POST requests via :class:`request`"""
        return self.request('direct_messages/events/new', 'POST', params='{"event": {"type": "message_create",
	"message_create": {"target": {"recipient_id": "111111111"}, "message_data": {"text": "Test"}}}}',
	version=version, json_encoded=json_encoded)

```

**Comment by parikshitsharma70** [comment]
Now the params is in the form of a string, so if you want to dynamically assign the recipient  ID and text  you can just  use `'....'+myVariable+'...'`
