### ISSUE TITLE
GitHub tags missing

### ISSUE THREAD

**Issue by jayvdb** [ryanmcgrath/twython#506]
c.f. https://github.com/ryanmcgrath/twython/issues/354 , tags are missing from v3.3 to current v3.7

**Comment by jayvdb** [comment]
ping @ryanmcgrath .

https://build.opensuse.org/request/show/673135 is sort of waiting for this.

**Comment by ryanmcgrath** [comment]
Sup.

I don't have time for this library right now, and I'm pretty sure @michaelhelmick is busy with his own life stuff. I'll ping Mike about contributors again, but concurrently, if my glancing over your linked thread is correct, what's wrong with just following master for now?

**Comment by jayvdb** [comment]
Takes only a few minutes to add a tag for the most recent release.

That would suffice for my needs.

**Comment by ryanmcgrath** [comment]
Sup.

Protip: "takes only a few minutes" is condescending and kinda unwarranted, and your comments in that openSUSE thread also come across as the same. People have lives outside of GitHub and software, and what might seem like only a few minutes can be a completely unnecessary distraction to someone else.

This'll get done whenever another maintainer has time. I'll poke Mike about new ones again.

**Comment by michaelhelmick** [comment]
A new tag has been released, sorry for the wait @jayvdb 
https://github.com/ryanmcgrath/twython/releases/tag/3.7.0

**Comment by jayvdb** [comment]
Thanks @michaelhelmick 	.  Package resubmitted at https://build.opensuse.org/request/show/689955 .  Hopefully I have better luck this time, so I can move on to fixing the nltk package which uses twython.
