### ISSUE TITLE
404 from user stream 

### ISSUE THREAD

**Issue by andrewtatham** [ryanmcgrath/twython#512]
Hi,

My bots have been offline for almost a year now. Trying to start them back up again. Got all my packages up-to-date. Using Twython v3.7.0 I'm getting a 404 from stream.user()...

Has the user stream been removed or something? I cant seem to find much reference to it in the twitter docs anymore. 

```
from twython import TwythonStreamer


class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            print(data['text'])

    def on_error(self, status_code, data):
        print(str(status_code) + ' ' + str(data))
        self.disconnect()


APP_KEY = tokens['APP_KEY']
APP_SECRET = tokens['APP_SECRET']
OAUTH_TOKEN = tokens['OAUTH_TOKEN']
OAUTH_TOKEN_SECRET = tokens['OAUTH_TOKEN_SECRET']

stream = MyStreamer(APP_KEY, APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

# stream.statuses.sample()  # works fine

stream.user()  # 404 b''
```
Or am I missing something?

Thanks

Andrew

**Comment by ryanmcgrath** [comment]
Closing as Twitter deprecated the user stream some time ago (and this is now old).
