### ISSUE TITLE
Error while uploading video on twitter

### ISSUE THREAD

**Issue by MyNameIsDark01** [ryanmcgrath/twython#524]
I'm using this code to upload a video:

> video = open('NewsBR.mp4', 'rb')
>                 response = twitter.upload_video(media=video, media_type='video/mp4', media_category='tweet_video', check_progress=True)
>                 twitter.update_status(status='check out this video', media_ids=[response['media_id']])

But it gives me this error:

> twython.exceptions.TwythonError: Twitter API returned a 400 (Bad Request), Not valid video

How can I solve this issue?

**Comment by ryanmcgrath** [comment]
Unfortunately, without knowing much about the video in question, there's nothing that can be done here.

This is also a few months old with no more activity, so I'm opting to close it. Hope you found what you needed.
