### ISSUE TITLE
OAuth1 Handling Callback

### ISSUE THREAD

**Issue by grantinator** [ryanmcgrath/twython#525]
I am new to OAuth, but it looks like in the 'starting out' django is used to get a piece of the callback url in the requests.GET('oauth_verifier'). I am wondering where/how the requests object is created, as this line of code seems entirely separated from all previous steps regarding the OAuth. 

'requests.get('oauh_verifier')' seems to go to the Twitter verification page, allow the app, then go to the callback url, then extract the relevant data from the callback url. This is the step I am unsure how to do. 

Here is what I am looking at.

```
APP_KEY = 'KEY'                                           
APP_SECRET = 'SECRET'               
                                                                                
twitter = Twython(APP_KEY, APP_SECRET)                                          
auth = twitter.get_authentication_tokens(callback_url='https://www.callback.com')                                                

OAUTH_TOKEN = auth['oauth_token']
OAUTH_TOKEN_SECRET = auth['oauth_token_secret']

## I am lost here
oauth_verifier = requests.GET['oauth_verifier']
##

twitter = Twython(APP_KEY, APP_SECRET,
                  OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

final_step = twitter.get_authorized_tokens(oauth_verifier)

OAUTH_TOKEN = final_step['oauth_token']
OAUTH_TOKEN_SECRET = final_step['oauth_token_secret']
```

**Comment by ryanmcgrath** [comment]
I realize this is from January, so hoping you found your answer, but to clear it up anyway: the `request` object in that case is provided by Django, identifying the return request in the OAuth handshake.

If you've not already, I'd encourage getting up to speed here: [Django](https://www.djangoproject.com)
