### ISSUE TITLE
Missing 'HISTORY.md' in source tarball on Pypi

### ISSUE THREAD

**Issue by ponsfoot** [ryanmcgrath/twython#529]
'HISTORY.md' is not existent in [twython-3.8.0.tar.gz](https://files.pythonhosted.org/packages/0d/74/8405f8aa35661abed11138f3cc42817017e8cec8f8c9e61c08ae8e717c3c/twython-3.8.0.tar.gz) so setup.py fails:

> Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    long_description=open('README.md', encoding='utf-8').read() + '\n\n' +open('HISTORY.md', encoding='utf-8').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'

Platform: ArchLinux

**Comment by ryanmcgrath** [comment]
Yeah, seems I forgot to update the Manifest file before publishing. I did so and bumped 3.8.1.

Lot of minor packaging changes since the last time it was pushed to Pypi, so something like this was bound to happen. If anything else pops up open another issue.
