### ISSUE TITLE
Recent changes to the streaming api broke the code base

### ISSUE THREAD

**Issue by bianjiang** [ryanmcgrath/twython#530]
Need to remove these two in the streaming/api.py

```python
self.user = StreamTypes.user
self.site = StreamTypes.site
```

https://github.com/ryanmcgrath/twython/blob/9ccc57622121b102b41b05d7e19024d5cfa835f9/twython/streaming/api.py#L89

**Comment by ryanmcgrath** [comment]
Fixed.
