### ISSUE TITLE
Python 2.x support

### ISSUE THREAD

**Issue by jvanasco** [ryanmcgrath/twython#533]
It looks like you killed Python 2.x support a few months back.

* it would be great to note in docs that this is Python3+ as of 3.8.0 ; some of us have legacy apps still running!
* `setup.py` still points to a python2 classifier, which should be removed as PyPi/etc gets populated with that.

**Comment by michaelhelmick** [comment]
Hm. I’ll double check this and try and clean that up soon! Sorry about that!

**Comment by tumbleweedlabs** [comment]
Any update on this? I'm trying to install Twython on a clean raspberry pi OS lite build and getting no love. Tried PIP, Easy Install, and building from source.

**Comment by jvanasco** [comment]
@tumbleweedlabs this ticket is for updating some classifiers (and human text) to say Twython no longer works with Python 2.7.x -- as they mark the project supporting Python27 on PyPi but it no longer does.

If you need to run it on Python 2.7.x, the last version that works AFAIK is 3.7.0.  I'm using that in a py27 production environment

    pip install twython==3.7.0

**Comment by nickycutesc** [comment]
I can confirm that this the above command works!

**Comment by chrstphrchvz** [comment]
Does #534 fix this issue?

**Comment by jvanasco** [comment]
I don't think that PR will be accepted - this project purposefully decided to drop Python2.x support.

That was not handled fully though.

This issue to to remove this line:

https://github.com/ryanmcgrath/twython/blob/master/setup.py#L45

And have the readme updated to reflect the last version that is supported under Python2.7 (release 3.7)

**Comment by ryanmcgrath** [comment]
This should be cleaned up and the README includes a note regarding the last 2.7 release.
