### ISSUE TITLE
Remove nose-cov dependency?

### ISSUE THREAD

**Issue by ppfeister** [ryanmcgrath/twython#553]
Hey Ryan

So, this package is a dependency of a dependency of a dependency of a dependency of a package I'm preparing for distribution on Fedora and Enterprise Linux. 

nose-cov, as a package, has been dead for far loner than twython. When looking at the source, I don't see that package being used anywhere. Is it being used as a dependency of one of your dependencies? Is this something that we would be able to safely remove from the requires?

**Comment by ppfeister** [comment]
It's in the travis.yaml -- disregard

**Comment by ryanmcgrath** [comment]
…what thing are you packaging that depends on this?

I guess it could be removed if it’s a formality - if it’s there it’s probably a decade or so old and I’d have no context beyond that lol

**Comment by ppfeister** [comment]
I have an ongoing project that will likely require [TextBlob](https://github.com/sloria/TextBlob), whose only dependency is [nltk](https://github.com/nltk/nltk), who then requires [twython](https://github.com/ryanmcgrath/twython). One layer less than I thought on this chain but /shrug/

If we're not sure how removal will impact things, then it's probably easier for me to adopt the [orphaned package](https://src.fedoraproject.org/rpms/python-nose-cov/) on Fedora and bring it back to life

Preparing the dependency coveralls for distrib now, for a similar reason -- doesn't seem as sure of a thing to remove
